-- ============================================================================
-- FIX for reset-to-france-mid-range.sql failure
--
-- The original SQL tried to DELETE FROM sets directly, expecting the
-- ON DELETE CASCADE on set_assignments.set_id to clean up the
-- assignment rows. Initial.sql declares the constraint with
-- ON DELETE CASCADE, but the live database has it as RESTRICT (or
-- NO ACTION) — Supabase migration drift. The cascade never fires and
-- the DELETE bombs with:
--
--   ERROR: 23503: update or delete on table "sets" violates foreign
--   key constraint "set_assignments_set_id_fkey" on table
--   "set_assignments"
--
-- This fix:
--   1. Deletes set_assignments + itinerary_items + plans + sets
--      EXPLICITLY in dependency order (no reliance on cascade).
--   2. Deletes non-Sofía travelers.
--   3. Inserts the 15 new travelers with ON CONFLICT (id) DO NOTHING
--      so a partial run that already inserted some rows can be re-run
--      cleanly.
--   4. Idempotently re-applies the Sofía mid-range upgrade.
--
-- Run THIS file (not the original) in Supabase. After this lands,
-- the original `reset-to-france-mid-range.sql` is superseded.
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────
-- SECTION 1 · Sofía mid-range upgrade (idempotent)
-- ────────────────────────────────────────────────────────────────────────
UPDATE public.travelers
SET    budget_per_day = 150,
       hotel_budget   = 140,
       meta = meta || jsonb_build_object(
         'budget_tier',                   'mid_range',
         'daily_spend_per_pax_eur',       150,
         'hotel_budget_per_night_pax_eur',140,
         'splurge_willingness',           'occasional',
         'booking_authority',             'planner_recommends',
         'pace',                          'moderate',
         'intensity',                     'moderate',
         'daily_timing',                  'standard',
         'previous_visits',               'first_time',
         'mobility',                      'none',
         'dietary_restrictions',          'none',
         'languages',                     to_jsonb(ARRAY['Spanish','English']::text[]),
         'occasion',                      'solo_travel',
         'accommodation_type',            'boutique',
         'room_type',                     'Private room with breakfast',
         'accommodation_musthaves',       to_jsonb(ARRAY['Central location','Wifi','Quiet street','Photo-iconic views']::text[]),
         'dining_style',                  'local_authentic',
         'cuisine_interests',             to_jsonb(ARRAY['Local bistros','Pastries','Cafes','Crêpes','Wine bars']::text[])
       )
WHERE  meta->>'seed_batch' = '01' AND meta->>'person_id' = '02';


-- ────────────────────────────────────────────────────────────────────────
-- SECTION 2 · Explicit cascade wipe (no FK cascade reliance)
-- ────────────────────────────────────────────────────────────────────────
-- Order: assignments → items → plans → sets → travelers.
-- All filter on "NOT linked to Sofía" via a single CTE we re-use.

WITH sofia AS (
  SELECT id FROM public.travelers
  WHERE  meta->>'seed_batch' = '01' AND meta->>'person_id' = '02'
),
non_sofia_plans AS (
  SELECT id, set_id FROM public.plans
  WHERE  traveler_id IS NULL
     OR  traveler_id NOT IN (SELECT id FROM sofia)
),
non_sofia_sets AS (
  -- Sets that have at least one non-Sofía plan AND no Sofía plan.
  -- Mixed sets (Sofía + others) keep the set; only the non-Sofía
  -- plan rows in them get deleted in the next step.
  SELECT DISTINCT s.id FROM public.sets s
  WHERE  NOT EXISTS (
    SELECT 1 FROM public.plans p
    WHERE  p.set_id = s.id AND p.traveler_id IN (SELECT id FROM sofia)
  )
)
-- 2a. Wipe set_assignments for non-Sofía sets (the FK that was blocking).
DELETE FROM public.set_assignments
WHERE  set_id IN (SELECT id FROM non_sofia_sets);

-- 2b. Wipe itinerary_items for non-Sofía plans.
DELETE FROM public.itinerary_items
WHERE  plan_id IN (
  SELECT id FROM public.plans
  WHERE  traveler_id IS NULL
     OR  traveler_id NOT IN (
       SELECT id FROM public.travelers
       WHERE  meta->>'seed_batch' = '01' AND meta->>'person_id' = '02'
     )
);

-- 2c. Wipe plans for non-Sofía travelers (or orphan plans).
DELETE FROM public.plans
WHERE  traveler_id IS NULL
   OR  traveler_id NOT IN (
     SELECT id FROM public.travelers
     WHERE  meta->>'seed_batch' = '01' AND meta->>'person_id' = '02'
   );

-- 2d. Wipe sets that now have no plan at all (orphan sets).
DELETE FROM public.sets
WHERE  NOT EXISTS (
  SELECT 1 FROM public.plans p WHERE p.set_id = sets.id
);

-- 2e. Wipe travelers (the last step, FKs are clean now).
DELETE FROM public.travelers
WHERE  NOT (meta->>'seed_batch' = '01' AND meta->>'person_id' = '02');


-- ────────────────────────────────────────────────────────────────────────
-- SECTION 3 · Insert 15 new travelers with ON CONFLICT DO NOTHING
-- ────────────────────────────────────────────────────────────────────────
-- ON CONFLICT (id) DO NOTHING — re-running this section is now safe.
-- If a previous partial run already inserted some persons (3-17), the
-- duplicate rows are silently skipped instead of throwing a 23505.
INSERT INTO public.travelers (id, name, phone, destination, traveler_type, arrival_date, arrival_time, duration, group_size, special_notes, status, planner_payout, requires_bond, bond_amount, meta) VALUES

-- ── 03 · Emily & James Carter · UK · Honeymoon · Paris + Bordeaux ──
('a0000001-0000-4000-8000-000300010000','Emily & James Carter','+44-7700-900123','Paris','honeymoon','2026-06-15','14:00','3D2N',2,'First trip together after our wedding. Want it to feel special but not Instagram-curated.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"03","unit_order":1,"unit_total":2,"trip_start_date":"2026-06-15","trip_end_date":"2026-06-20","origin_country":"United Kingdom","origin_city":"London","ages":[33,35],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":170,"hotel_budget_per_night_pax_eur":160,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"honeymoon","interests":["art_museums","food_wine","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Junior suite","accommodation_musthaves":["Quiet street","King bed","Bathtub","Central location"],"dining_style":"local_authentic","cuisine_interests":["Wine bars","Bistros","Patisseries"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"London, United Kingdom","unit_departure_method":"train","unit_departure_location":"Paris Gare Montparnasse","unit_departure_to":"Bordeaux","unit_departure_date":"2026-06-17","unit_departure_time":"11:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000300020000','Emily & James Carter','+44-7700-900123','Bordeaux','honeymoon','2026-06-17','13:30','3D2N',2,'First trip together after our wedding. Want it to feel special but not Instagram-curated.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"03","unit_order":2,"unit_total":2,"trip_start_date":"2026-06-15","trip_end_date":"2026-06-20","origin_country":"United Kingdom","origin_city":"London","ages":[33,35],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":170,"hotel_budget_per_night_pax_eur":160,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"honeymoon","interests":["food_wine","villages","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Junior suite","accommodation_musthaves":["Vineyard view","King bed","Bathtub"],"dining_style":"local_authentic","cuisine_interests":["Wine cellars","Bistros","Chateaux dining"],"unit_arrival_method":"train","unit_arrival_location":"Bordeaux Saint-Jean","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"BOD","unit_departure_to":"London, United Kingdom","unit_departure_date":"2026-06-20","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 04 · Lukas Müller · Berlin · Solo · Paris + Strasbourg ──
('a0000001-0000-4000-8000-000400010000','Lukas Müller','+49-151-2345-6789','Paris','solo','2026-06-22','13:45','3D2N',1,'Architect on sabbatical. Looking for hidden modernist gems alongside the canon.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"04","unit_order":1,"unit_total":2,"trip_start_date":"2026-06-22","trip_end_date":"2026-06-26","origin_country":"Germany","origin_city":"Berlin","ages":[32],"languages":["German","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":145,"hotel_budget_per_night_pax_eur":130,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["architecture","photography","art_museums","hidden_gems"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Single room","accommodation_musthaves":["Wifi","Quiet street","Workspace"],"dining_style":"local_authentic","cuisine_interests":["Brasseries","Cafes","Market food"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Berlin, Germany","unit_departure_method":"train","unit_departure_location":"Paris Gare de l Est","unit_departure_to":"Strasbourg","unit_departure_date":"2026-06-25","unit_departure_time":"09:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000400020000','Lukas Müller','+49-151-2345-6789','Strasbourg','solo','2026-06-25','11:00','2D1N',1,'Architect on sabbatical. Looking for hidden modernist gems alongside the canon.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"04","unit_order":2,"unit_total":2,"trip_start_date":"2026-06-22","trip_end_date":"2026-06-26","origin_country":"Germany","origin_city":"Berlin","ages":[32],"languages":["German","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":145,"hotel_budget_per_night_pax_eur":130,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["architecture","photography","villages"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Single room","accommodation_musthaves":["Wifi","Central location"],"dining_style":"local_authentic","cuisine_interests":["Winstubs","Choucroute","Tarte flambée"],"unit_arrival_method":"train","unit_arrival_location":"Strasbourg Gare","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"SXB","unit_departure_to":"Berlin, Germany","unit_departure_date":"2026-06-26","unit_departure_time":"16:30","airport_buffer_minutes":180}'::jsonb),

-- ── 05 · Wei Lin & Marcus Tan · Singapore · Honeymoon · Paris+Nice+Cannes ──
('a0000001-0000-4000-8000-000500010000','Wei Lin & Marcus Tan','+65-9123-4567','Paris','honeymoon','2026-07-03','14:30','3D2N',2,'Long-haul honeymoon — comfort matters. We love a good tasting menu but skip the snobby ones.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"05","unit_order":1,"unit_total":3,"trip_start_date":"2026-07-03","trip_end_date":"2026-07-11","origin_country":"Singapore","origin_city":"Singapore","ages":[29,31],"languages":["English","Mandarin"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":180,"hotel_budget_per_night_pax_eur":170,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"honeymoon","interests":["food_wine","art_museums","architecture","photography"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Junior suite","accommodation_musthaves":["Iconic view","King bed","Concierge"],"dining_style":"michelin_dining","cuisine_interests":["Michelin","Wine tasting","Pastries"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Singapore","unit_departure_method":"train","unit_departure_location":"Paris Gare de Lyon","unit_departure_to":"Nice","unit_departure_date":"2026-07-05","unit_departure_time":"10:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000500020000','Wei Lin & Marcus Tan','+65-9123-4567','Nice','honeymoon','2026-07-05','16:00','3D2N',2,'Long-haul honeymoon — comfort matters. We love a good tasting menu but skip the snobby ones.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"05","unit_order":2,"unit_total":3,"trip_start_date":"2026-07-03","trip_end_date":"2026-07-11","origin_country":"Singapore","origin_city":"Singapore","ages":[29,31],"languages":["English","Mandarin"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":180,"hotel_budget_per_night_pax_eur":170,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"honeymoon","interests":["beach","food_wine","photography","villages"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Sea-view suite","accommodation_musthaves":["Sea view","King bed","Balcony"],"dining_style":"michelin_dining","cuisine_interests":["Niçoise","Seafood","Riviera classics"],"unit_arrival_method":"train","unit_arrival_location":"Nice Ville","unit_arrival_from":"Paris","unit_departure_method":"train","unit_departure_location":"Nice Ville","unit_departure_to":"Cannes","unit_departure_date":"2026-07-08","unit_departure_time":"11:00","airport_buffer_minutes":60}'::jsonb),
('a0000001-0000-4000-8000-000500030000','Wei Lin & Marcus Tan','+65-9123-4567','Cannes','honeymoon','2026-07-08','12:00','2D1N',2,'Long-haul honeymoon — comfort matters. We love a good tasting menu but skip the snobby ones.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"05","unit_order":3,"unit_total":3,"trip_start_date":"2026-07-03","trip_end_date":"2026-07-11","origin_country":"Singapore","origin_city":"Singapore","ages":[29,31],"languages":["English","Mandarin"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":180,"hotel_budget_per_night_pax_eur":170,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"honeymoon","interests":["beach","food_wine","photography"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Sea-view suite","accommodation_musthaves":["Sea view","King bed","Balcony"],"dining_style":"michelin_dining","cuisine_interests":["Seafood","Riviera classics","Cocktails"],"unit_arrival_method":"train","unit_arrival_location":"Cannes Gare","unit_arrival_from":"Nice","unit_departure_method":"flight","unit_departure_location":"NCE","unit_departure_to":"Singapore","unit_departure_date":"2026-07-09","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 06 · Olivia & Mark Thompson + kids · Boston USA · Family · Paris+Avignon ──
('a0000001-0000-4000-8000-000600010000','Olivia & Mark Thompson','+1-617-555-0142','Paris','family','2026-07-12','14:15','3D2N',4,'Two parents, two kids (10, 12). First time abroad for the kids — interest level: high, attention span: variable.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"06","unit_order":1,"unit_total":2,"trip_start_date":"2026-07-12","trip_end_date":"2026-07-17","origin_country":"United States","origin_city":"Boston","ages":[42,40,12,10],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":135,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"light_walking","daily_timing":"standard","occasion":"family_holiday","interests":["art_museums","architecture","food_wine"],"dietary_restrictions":"none","accommodation_type":"hotel","room_type":"Family room (2 beds)","accommodation_musthaves":["Family room","Wifi","Breakfast included","Central location"],"dining_style":"familiar_comfort","cuisine_interests":["Family bistros","Boulangeries","Crêpes","Glaces"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Boston, United States","unit_departure_method":"train","unit_departure_location":"Paris Gare de Lyon","unit_departure_to":"Avignon","unit_departure_date":"2026-07-14","unit_departure_time":"11:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000600020000','Olivia & Mark Thompson','+1-617-555-0142','Avignon','family','2026-07-14','14:00','3D2N',4,'Two parents, two kids (10, 12). First time abroad for the kids — interest level: high, attention span: variable.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"06","unit_order":2,"unit_total":2,"trip_start_date":"2026-07-12","trip_end_date":"2026-07-17","origin_country":"United States","origin_city":"Boston","ages":[42,40,12,10],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":135,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"light_walking","daily_timing":"standard","occasion":"family_holiday","interests":["villages","photography","food_wine","châteaux"],"dietary_restrictions":"none","accommodation_type":"hotel","room_type":"Family room (2 beds)","accommodation_musthaves":["Family room","Pool","Breakfast"],"dining_style":"familiar_comfort","cuisine_interests":["Provençal","Boulangeries","Glaces"],"unit_arrival_method":"train","unit_arrival_location":"Avignon TGV","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"MRS","unit_departure_to":"Boston, United States","unit_departure_date":"2026-07-17","unit_departure_time":"16:00","airport_buffer_minutes":180}'::jsonb),

-- ── 07 · Ji-hye Park · Seoul · Solo · Paris + Lyon ──
('a0000001-0000-4000-8000-000700010000','Ji-hye Park','+82-10-2345-6789','Paris','solo','2026-07-19','13:50','3D2N',1,'Designer escaping Seoul deadlines. Photography + museums by day, good wine by night.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"07","unit_order":1,"unit_total":2,"trip_start_date":"2026-07-19","trip_end_date":"2026-07-23","origin_country":"South Korea","origin_city":"Seoul","ages":[29],"languages":["Korean","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":140,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["art_museums","photography","cafes","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Single room","accommodation_musthaves":["Wifi","Quiet","Photo-iconic neighborhood"],"dining_style":"local_authentic","cuisine_interests":["Cafes","Patisseries","Brasseries"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Seoul, South Korea","unit_departure_method":"train","unit_departure_location":"Paris Gare de Lyon","unit_departure_to":"Lyon","unit_departure_date":"2026-07-22","unit_departure_time":"09:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000700020000','Ji-hye Park','+82-10-2345-6789','Lyon','solo','2026-07-22','11:00','2D1N',1,'Designer escaping Seoul deadlines. Photography + museums by day, good wine by night.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"07","unit_order":2,"unit_total":2,"trip_start_date":"2026-07-19","trip_end_date":"2026-07-23","origin_country":"South Korea","origin_city":"Seoul","ages":[29],"languages":["Korean","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":140,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["food_wine","photography","villages","hidden_gems"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Single room","accommodation_musthaves":["Wifi","Central location"],"dining_style":"local_authentic","cuisine_interests":["Bouchons","Wine bars","Pralines"],"unit_arrival_method":"train","unit_arrival_location":"Lyon Part-Dieu","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"LYS","unit_departure_to":"Seoul, South Korea","unit_departure_date":"2026-07-23","unit_departure_time":"17:30","airport_buffer_minutes":180}'::jsonb),

-- ── 08 · Camila & Diego Vargas · Bogotá · Anniversary · Paris+Reims ──
('a0000001-0000-4000-8000-000800010000','Camila & Diego Vargas','+57-310-555-2347','Paris','couple','2026-07-24','14:30','3D2N',2,'10 years married. We do a "real" trip every five — last was Tokyo, this is France. Champagne is non-negotiable.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"08","unit_order":1,"unit_total":2,"trip_start_date":"2026-07-24","trip_end_date":"2026-07-28","origin_country":"Colombia","origin_city":"Bogotá","ages":[30,32],"languages":["Spanish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":160,"hotel_budget_per_night_pax_eur":145,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"relaxed","intensity":"light_walking","daily_timing":"standard","occasion":"anniversary","interests":["art_museums","food_wine","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Double room","accommodation_musthaves":["Central location","King bed","Bathtub"],"dining_style":"local_authentic","cuisine_interests":["Bistros","Wine bars","Patisseries"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Bogotá, Colombia","unit_departure_method":"train","unit_departure_location":"Paris Gare de l Est","unit_departure_to":"Reims","unit_departure_date":"2026-07-27","unit_departure_time":"10:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000800020000','Camila & Diego Vargas','+57-310-555-2347','Reims','couple','2026-07-27','11:00','2D1N',2,'10 years married. We do a "real" trip every five — last was Tokyo, this is France. Champagne is non-negotiable.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"08","unit_order":2,"unit_total":2,"trip_start_date":"2026-07-24","trip_end_date":"2026-07-28","origin_country":"Colombia","origin_city":"Bogotá","ages":[30,32],"languages":["Spanish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":160,"hotel_budget_per_night_pax_eur":145,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"relaxed","intensity":"light_walking","daily_timing":"standard","occasion":"anniversary","interests":["food_wine","villages","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Double room","accommodation_musthaves":["Quiet","King bed","Champagne house view"],"dining_style":"local_authentic","cuisine_interests":["Champagne cellars","Bistros","Patisseries"],"unit_arrival_method":"train","unit_arrival_location":"Reims Gare","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"CDG","unit_departure_to":"Bogotá, Colombia","unit_departure_date":"2026-07-28","unit_departure_time":"16:00","airport_buffer_minutes":180}'::jsonb),

-- ── 09 · Eduardo & Beatriz Silva · São Paulo · Wine · Bordeaux + Lyon ──
('a0000001-0000-4000-8000-000900010000','Eduardo & Beatriz Silva','+55-11-9876-5432','Bordeaux','couple','2026-07-29','14:00','3D2N',2,'Wine importers from São Paulo. We know what we like; please don''t take us to anywhere with a sommelier who lectures.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"09","unit_order":1,"unit_total":2,"trip_start_date":"2026-07-29","trip_end_date":"2026-08-04","origin_country":"Brazil","origin_city":"São Paulo","ages":[38,36],"languages":["Portuguese","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":175,"hotel_budget_per_night_pax_eur":155,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"wine_pilgrimage","interests":["food_wine","villages","architecture","châteaux"],"dietary_restrictions":"none","accommodation_type":"villa","room_type":"Vineyard chateau room","accommodation_musthaves":["Vineyard view","Pool","Breakfast"],"dining_style":"local_authentic","cuisine_interests":["Wine cellars","Chateaux dining","Bistros"],"unit_arrival_method":"flight","unit_arrival_location":"BOD","unit_arrival_from":"São Paulo, Brazil","unit_departure_method":"train","unit_departure_location":"Bordeaux Saint-Jean","unit_departure_to":"Lyon","unit_departure_date":"2026-08-01","unit_departure_time":"10:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-000900020000','Eduardo & Beatriz Silva','+55-11-9876-5432','Lyon','couple','2026-08-01','14:30','3D2N',2,'Wine importers from São Paulo. We know what we like; please don''t take us to anywhere with a sommelier who lectures.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"09","unit_order":2,"unit_total":2,"trip_start_date":"2026-07-29","trip_end_date":"2026-08-04","origin_country":"Brazil","origin_city":"São Paulo","ages":[38,36],"languages":["Portuguese","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":175,"hotel_budget_per_night_pax_eur":155,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"wine_pilgrimage","interests":["food_wine","villages","cuisine"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Double room","accommodation_musthaves":["Old town view","King bed","Bathtub"],"dining_style":"local_authentic","cuisine_interests":["Bouchons","Wine bars","Michelin","Pralines"],"unit_arrival_method":"train","unit_arrival_location":"Lyon Part-Dieu","unit_arrival_from":"Bordeaux","unit_departure_method":"flight","unit_departure_location":"LYS","unit_departure_to":"São Paulo, Brazil","unit_departure_date":"2026-08-04","unit_departure_time":"16:00","airport_buffer_minutes":180}'::jsonb),

-- ── 10 · Anna Kowalski · Warsaw · Solo · Lyon + Annecy ──
('a0000001-0000-4000-8000-001000010000','Anna Kowalski','+48-501-234-567','Lyon','solo','2026-08-05','14:00','3D2N',1,'Software engineer treating myself before starting a new role. Want to eat well and walk a lot.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"10","unit_order":1,"unit_total":2,"trip_start_date":"2026-08-05","trip_end_date":"2026-08-09","origin_country":"Poland","origin_city":"Warsaw","ages":[31],"languages":["Polish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":130,"hotel_budget_per_night_pax_eur":115,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["food_wine","hidden_gems","villages","photography"],"dietary_restrictions":"none","accommodation_type":"airbnb","room_type":"Private studio","accommodation_musthaves":["Central location","Wifi","Kitchen"],"dining_style":"local_authentic","cuisine_interests":["Bouchons","Cafes","Market food"],"unit_arrival_method":"flight","unit_arrival_location":"LYS","unit_arrival_from":"Warsaw, Poland","unit_departure_method":"train","unit_departure_location":"Lyon Part-Dieu","unit_departure_to":"Annecy","unit_departure_date":"2026-08-08","unit_departure_time":"09:30","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001000020000','Anna Kowalski','+48-501-234-567','Annecy','solo','2026-08-08','11:30','2D1N',1,'Software engineer treating myself before starting a new role. Want to eat well and walk a lot.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"10","unit_order":2,"unit_total":2,"trip_start_date":"2026-08-05","trip_end_date":"2026-08-09","origin_country":"Poland","origin_city":"Warsaw","ages":[31],"languages":["Polish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":130,"hotel_budget_per_night_pax_eur":115,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["villages","photography","food_wine","hiking"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Lake-view room","accommodation_musthaves":["Lake view","Wifi","Quiet"],"dining_style":"local_authentic","cuisine_interests":["Savoyard","Cafes","Boulangeries"],"unit_arrival_method":"train","unit_arrival_location":"Annecy Gare","unit_arrival_from":"Lyon","unit_departure_method":"flight","unit_departure_location":"LYS","unit_departure_to":"Warsaw, Poland","unit_departure_date":"2026-08-09","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 11 · Rachel & David Cohen · Tel Aviv · Anniversary · Paris+Marseille+Avignon ──
('a0000001-0000-4000-8000-001100010000','Rachel & David Cohen','+972-50-555-1234','Paris','couple','2026-08-10','14:00','3D2N',2,'25th anniversary trip. Architects, both of us — please pick stops with stories, not just photos.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"11","unit_order":1,"unit_total":3,"trip_start_date":"2026-08-10","trip_end_date":"2026-08-16","origin_country":"Israel","origin_city":"Tel Aviv","ages":[45,47],"languages":["Hebrew","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":165,"hotel_budget_per_night_pax_eur":150,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["architecture","art_museums","photography","food_wine"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Suite","accommodation_musthaves":["King bed","Bathtub","Concierge"],"dining_style":"local_authentic","cuisine_interests":["Bistros","Wine bars","Mediterranean"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Tel Aviv, Israel","unit_departure_method":"train","unit_departure_location":"Paris Gare de Lyon","unit_departure_to":"Marseille","unit_departure_date":"2026-08-12","unit_departure_time":"09:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001100020000','Rachel & David Cohen','+972-50-555-1234','Marseille','couple','2026-08-12','12:30','2D1N',2,'25th anniversary trip. Architects, both of us — please pick stops with stories, not just photos.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"11","unit_order":2,"unit_total":3,"trip_start_date":"2026-08-10","trip_end_date":"2026-08-16","origin_country":"Israel","origin_city":"Tel Aviv","ages":[45,47],"languages":["Hebrew","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":165,"hotel_budget_per_night_pax_eur":150,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["architecture","photography","food_wine","beach"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Sea-view suite","accommodation_musthaves":["Sea view","King bed","Quiet"],"dining_style":"local_authentic","cuisine_interests":["Bouillabaisse","Seafood","Provençal"],"unit_arrival_method":"train","unit_arrival_location":"Marseille Saint-Charles","unit_arrival_from":"Paris","unit_departure_method":"train","unit_departure_location":"Marseille Saint-Charles","unit_departure_to":"Avignon","unit_departure_date":"2026-08-14","unit_departure_time":"10:30","airport_buffer_minutes":60}'::jsonb),
('a0000001-0000-4000-8000-001100030000','Rachel & David Cohen','+972-50-555-1234','Avignon','couple','2026-08-14','11:30','2D1N',2,'25th anniversary trip. Architects, both of us — please pick stops with stories, not just photos.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"11","unit_order":3,"unit_total":3,"trip_start_date":"2026-08-10","trip_end_date":"2026-08-16","origin_country":"Israel","origin_city":"Tel Aviv","ages":[45,47],"languages":["Hebrew","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":165,"hotel_budget_per_night_pax_eur":150,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["architecture","photography","villages","food_wine"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Old town suite","accommodation_musthaves":["Old town location","King bed","Bathtub"],"dining_style":"local_authentic","cuisine_interests":["Provençal","Wine bars","Truffles"],"unit_arrival_method":"train","unit_arrival_location":"Avignon TGV","unit_arrival_from":"Marseille","unit_departure_method":"flight","unit_departure_location":"MRS","unit_departure_to":"Tel Aviv, Israel","unit_departure_date":"2026-08-16","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 12 · Maria Eduarda Santos · Lisbon · Solo · Nice + Marseille ──
('a0000001-0000-4000-8000-001200010000','Maria Eduarda Santos','+351-91-234-5678','Nice','solo','2026-08-18','14:30','3D2N',1,'Travel writer scouting for a Riviera piece. Looking for the local angle, not the cruise-ship circuit.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"12","unit_order":1,"unit_total":2,"trip_start_date":"2026-08-18","trip_end_date":"2026-08-21","origin_country":"Portugal","origin_city":"Lisbon","ages":[26],"languages":["Portuguese","Spanish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":135,"hotel_budget_per_night_pax_eur":120,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["photography","beach","food_wine","hidden_gems"],"dietary_restrictions":"none","accommodation_type":"airbnb","room_type":"Studio with balcony","accommodation_musthaves":["Wifi","Quiet street","Workspace"],"dining_style":"local_authentic","cuisine_interests":["Niçoise","Seafood","Markets"],"unit_arrival_method":"flight","unit_arrival_location":"NCE","unit_arrival_from":"Lisbon, Portugal","unit_departure_method":"train","unit_departure_location":"Nice Ville","unit_departure_to":"Marseille","unit_departure_date":"2026-08-20","unit_departure_time":"09:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001200020000','Maria Eduarda Santos','+351-91-234-5678','Marseille','solo','2026-08-20','11:30','2D1N',1,'Travel writer scouting for a Riviera piece. Looking for the local angle, not the cruise-ship circuit.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"12","unit_order":2,"unit_total":2,"trip_start_date":"2026-08-18","trip_end_date":"2026-08-21","origin_country":"Portugal","origin_city":"Lisbon","ages":[26],"languages":["Portuguese","Spanish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":135,"hotel_budget_per_night_pax_eur":120,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["photography","beach","food_wine","hidden_gems"],"dietary_restrictions":"none","accommodation_type":"airbnb","room_type":"Studio","accommodation_musthaves":["Old port view","Wifi"],"dining_style":"local_authentic","cuisine_interests":["Bouillabaisse","Seafood","Markets"],"unit_arrival_method":"train","unit_arrival_location":"Marseille Saint-Charles","unit_arrival_from":"Nice","unit_departure_method":"flight","unit_departure_location":"MRS","unit_departure_to":"Lisbon, Portugal","unit_departure_date":"2026-08-21","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 13 · Klaas & Marieke Janssen · Amsterdam · Anniversary · Strasbourg + Reims ──
('a0000001-0000-4000-8000-001300010000','Klaas & Marieke Janssen','+31-6-1234-5678','Strasbourg','couple','2026-08-23','14:00','2D1N',2,'Cycling-trip people doing a slower one this year. Alsace then Champagne — keep it walkable.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"13","unit_order":1,"unit_total":2,"trip_start_date":"2026-08-23","trip_end_date":"2026-08-25","origin_country":"Netherlands","origin_city":"Amsterdam","ages":[41,39],"languages":["Dutch","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":155,"hotel_budget_per_night_pax_eur":140,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"relaxed","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["villages","food_wine","photography","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Double room","accommodation_musthaves":["Old town location","Bathtub","Breakfast"],"dining_style":"local_authentic","cuisine_interests":["Winstubs","Tarte flambée","Riesling"],"unit_arrival_method":"flight","unit_arrival_location":"SXB","unit_arrival_from":"Amsterdam, Netherlands","unit_departure_method":"train","unit_departure_location":"Strasbourg Gare","unit_departure_to":"Reims","unit_departure_date":"2026-08-24","unit_departure_time":"10:00","airport_buffer_minutes":60}'::jsonb),
('a0000001-0000-4000-8000-001300020000','Klaas & Marieke Janssen','+31-6-1234-5678','Reims','couple','2026-08-24','13:30','2D1N',2,'Cycling-trip people doing a slower one this year. Alsace then Champagne — keep it walkable.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"13","unit_order":2,"unit_total":2,"trip_start_date":"2026-08-23","trip_end_date":"2026-08-25","origin_country":"Netherlands","origin_city":"Amsterdam","ages":[41,39],"languages":["Dutch","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":155,"hotel_budget_per_night_pax_eur":140,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"relaxed","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["food_wine","villages","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Double room","accommodation_musthaves":["Champagne house view","Quiet","Breakfast"],"dining_style":"local_authentic","cuisine_interests":["Champagne cellars","Bistros","Patisseries"],"unit_arrival_method":"train","unit_arrival_location":"Reims Gare","unit_arrival_from":"Strasbourg","unit_departure_method":"flight","unit_departure_location":"CDG","unit_departure_to":"Amsterdam, Netherlands","unit_departure_date":"2026-08-25","unit_departure_time":"16:30","airport_buffer_minutes":180}'::jsonb),

-- ── 14 · Liam O'Connor · Dublin · Solo · Paris+Saint-Malo+MSM ──
('a0000001-0000-4000-8000-001400010000','Liam O''Connor','+353-86-234-5678','Paris','solo','2026-08-27','14:00','3D2N',1,'Game developer on his first proper holiday in two years. Loves quiet places near water.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"14","unit_order":1,"unit_total":3,"trip_start_date":"2026-08-27","trip_end_date":"2026-09-01","origin_country":"Ireland","origin_city":"Dublin","ages":[28],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":140,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["villages","photography","food_wine","hidden_gems"],"dietary_restrictions":"none","accommodation_type":"airbnb","room_type":"Studio","accommodation_musthaves":["Wifi","Quiet street","Workspace"],"dining_style":"local_authentic","cuisine_interests":["Bistros","Crêpes","Cafes"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Dublin, Ireland","unit_departure_method":"train","unit_departure_location":"Paris Gare Montparnasse","unit_departure_to":"Saint-Malo","unit_departure_date":"2026-08-29","unit_departure_time":"09:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001400020000','Liam O''Connor','+353-86-234-5678','Saint-Malo','solo','2026-08-29','12:00','2D1N',1,'Game developer on his first proper holiday in two years. Loves quiet places near water.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"14","unit_order":2,"unit_total":3,"trip_start_date":"2026-08-27","trip_end_date":"2026-09-01","origin_country":"Ireland","origin_city":"Dublin","ages":[28],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":140,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["villages","photography","food_wine","beach"],"dietary_restrictions":"none","accommodation_type":"airbnb","room_type":"Studio","accommodation_musthaves":["Sea view","Wifi","Quiet"],"dining_style":"local_authentic","cuisine_interests":["Seafood","Crêpes","Cider"],"unit_arrival_method":"train","unit_arrival_location":"Saint-Malo Station","unit_arrival_from":"Paris","unit_departure_method":"car","unit_departure_location":"Saint-Malo","unit_departure_to":"Mont-Saint-Michel","unit_departure_date":"2026-08-30","unit_departure_time":"11:00","airport_buffer_minutes":60}'::jsonb),
('a0000001-0000-4000-8000-001400030000','Liam O''Connor','+353-86-234-5678','Mont-Saint-Michel','solo','2026-08-30','12:00','2D1N',1,'Game developer on his first proper holiday in two years. Loves quiet places near water.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"14","unit_order":3,"unit_total":3,"trip_start_date":"2026-08-27","trip_end_date":"2026-09-01","origin_country":"Ireland","origin_city":"Dublin","ages":[28],"languages":["English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":140,"hotel_budget_per_night_pax_eur":125,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"active","intensity":"active","daily_timing":"standard","occasion":"solo_travel","interests":["villages","photography","hidden_gems"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Abbey-view room","accommodation_musthaves":["Abbey view","Quiet","Breakfast"],"dining_style":"local_authentic","cuisine_interests":["Omelette Mère Poulard","Cider","Seafood"],"unit_arrival_method":"car","unit_arrival_location":"Mont-Saint-Michel","unit_arrival_from":"Saint-Malo","unit_departure_method":"flight","unit_departure_location":"RNS","unit_departure_to":"Dublin, Ireland","unit_departure_date":"2026-08-31","unit_departure_time":"16:00","airport_buffer_minutes":180}'::jsonb),

-- ── 15 · Isabella & Marco Rossi · Milan · Anniversary · Nice + Marseille ──
('a0000001-0000-4000-8000-001500010000','Isabella & Marco Rossi','+39-340-123-4567','Nice','couple','2026-09-03','14:30','3D2N',2,'We do food trips. Italian palate, French neighbourhood — expect strong opinions about tomatoes.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"15","unit_order":1,"unit_total":2,"trip_start_date":"2026-09-03","trip_end_date":"2026-09-08","origin_country":"Italy","origin_city":"Milan","ages":[36,38],"languages":["Italian","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":170,"hotel_budget_per_night_pax_eur":155,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["food_wine","cuisine","beach","architecture"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Sea-view double","accommodation_musthaves":["Sea view","King bed","Balcony"],"dining_style":"local_authentic","cuisine_interests":["Niçoise","Seafood","Wine bars","Markets"],"unit_arrival_method":"flight","unit_arrival_location":"NCE","unit_arrival_from":"Milan, Italy","unit_departure_method":"train","unit_departure_location":"Nice Ville","unit_departure_to":"Marseille","unit_departure_date":"2026-09-06","unit_departure_time":"10:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001500020000','Isabella & Marco Rossi','+39-340-123-4567','Marseille','couple','2026-09-06','13:00','3D2N',2,'We do food trips. Italian palate, French neighbourhood — expect strong opinions about tomatoes.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"15","unit_order":2,"unit_total":2,"trip_start_date":"2026-09-03","trip_end_date":"2026-09-08","origin_country":"Italy","origin_city":"Milan","ages":[36,38],"languages":["Italian","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":170,"hotel_budget_per_night_pax_eur":155,"splurge_willingness":"occasional","booking_authority":"planner_recommends","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"anniversary","interests":["food_wine","cuisine","architecture","photography"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Old port suite","accommodation_musthaves":["Old port view","King bed","Quiet"],"dining_style":"local_authentic","cuisine_interests":["Bouillabaisse","Seafood","Provençal","Markets"],"unit_arrival_method":"train","unit_arrival_location":"Marseille Saint-Charles","unit_arrival_from":"Nice","unit_departure_method":"flight","unit_departure_location":"MRS","unit_departure_to":"Milan, Italy","unit_departure_date":"2026-09-08","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 16 · Sara Lindberg · Stockholm · Solo · Paris + Nantes ──
('a0000001-0000-4000-8000-001600010000','Sara Lindberg','+46-70-123-4567','Paris','solo','2026-09-09','14:00','3D2N',1,'Curator on a grant. Hidden museums + emerging artists. Big-museum hits already done.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"16","unit_order":1,"unit_total":2,"trip_start_date":"2026-09-09","trip_end_date":"2026-09-13","origin_country":"Sweden","origin_city":"Stockholm","ages":[27],"languages":["Swedish","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":145,"hotel_budget_per_night_pax_eur":130,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"solo_travel","interests":["art_museums","hidden_gems","food_wine","architecture"],"dietary_restrictions":"none","accommodation_type":"airbnb","room_type":"Studio with workspace","accommodation_musthaves":["Wifi","Quiet street","Workspace","Light"],"dining_style":"local_authentic","cuisine_interests":["Bistros","Wine bars","Cafes","Markets"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Stockholm, Sweden","unit_departure_method":"train","unit_departure_location":"Paris Gare Montparnasse","unit_departure_to":"Nantes","unit_departure_date":"2026-09-12","unit_departure_time":"09:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001600020000','Sara Lindberg','+46-70-123-4567','Nantes','solo','2026-09-12','11:30','2D1N',1,'Curator on a grant. Hidden museums + emerging artists. Big-museum hits already done.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"16","unit_order":2,"unit_total":2,"trip_start_date":"2026-09-09","trip_end_date":"2026-09-13","origin_country":"Sweden","origin_city":"Stockholm","ages":[27],"languages":["Swedish","English"],"mobility":"none","previous_visits":"repeat","budget_tier":"mid_range","daily_spend_per_pax_eur":145,"hotel_budget_per_night_pax_eur":130,"splurge_willingness":"occasional","booking_authority":"traveler_decides","pace":"moderate","intensity":"moderate","daily_timing":"standard","occasion":"solo_travel","interests":["art_museums","architecture","hidden_gems","photography"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Single","accommodation_musthaves":["Central location","Wifi","Quiet"],"dining_style":"local_authentic","cuisine_interests":["Bistros","Crêpes","Markets"],"unit_arrival_method":"train","unit_arrival_location":"Nantes Gare","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"NTE","unit_departure_to":"Stockholm, Sweden","unit_departure_date":"2026-09-13","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb),

-- ── 17 · Joaquín & Valentina Reyes · Santiago · Honeymoon · Paris + Avignon ──
('a0000001-0000-4000-8000-001700010000','Joaquín & Valentina Reyes','+56-9-1234-5678','Paris','honeymoon','2026-09-14','14:00','3D2N',2,'Married in March, saved for the honeymoon ever since. Provence is the dream — Paris is the warm-up.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"17","unit_order":1,"unit_total":2,"trip_start_date":"2026-09-14","trip_end_date":"2026-09-19","origin_country":"Chile","origin_city":"Santiago","ages":[28,27],"languages":["Spanish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":180,"hotel_budget_per_night_pax_eur":170,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"relaxed","intensity":"light_walking","daily_timing":"standard","occasion":"honeymoon","interests":["food_wine","architecture","art_museums","photography"],"dietary_restrictions":"none","accommodation_type":"boutique","room_type":"Junior suite","accommodation_musthaves":["Iconic view","King bed","Bathtub"],"dining_style":"michelin_dining","cuisine_interests":["Michelin","Wine tasting","Patisseries"],"unit_arrival_method":"flight","unit_arrival_location":"CDG","unit_arrival_from":"Santiago, Chile","unit_departure_method":"train","unit_departure_location":"Paris Gare de Lyon","unit_departure_to":"Avignon","unit_departure_date":"2026-09-16","unit_departure_time":"10:00","airport_buffer_minutes":180}'::jsonb),
('a0000001-0000-4000-8000-001700020000','Joaquín & Valentina Reyes','+56-9-1234-5678','Avignon','honeymoon','2026-09-16','13:00','3D2N',2,'Married in March, saved for the honeymoon ever since. Provence is the dream — Paris is the warm-up.','unassigned',48,false,NULL,
 '{"seed_batch":"02","person_id":"17","unit_order":2,"unit_total":2,"trip_start_date":"2026-09-14","trip_end_date":"2026-09-19","origin_country":"Chile","origin_city":"Santiago","ages":[28,27],"languages":["Spanish","English"],"mobility":"none","previous_visits":"first_time","budget_tier":"mid_range","daily_spend_per_pax_eur":180,"hotel_budget_per_night_pax_eur":170,"splurge_willingness":"frequent","booking_authority":"planner_recommends","pace":"relaxed","intensity":"light_walking","daily_timing":"standard","occasion":"honeymoon","interests":["villages","food_wine","photography","châteaux"],"dietary_restrictions":"none","accommodation_type":"villa","room_type":"Chateau suite","accommodation_musthaves":["Pool","Vineyard view","King bed","Breakfast"],"dining_style":"michelin_dining","cuisine_interests":["Provençal","Truffles","Wine tasting","Michelin"],"unit_arrival_method":"train","unit_arrival_location":"Avignon TGV","unit_arrival_from":"Paris","unit_departure_method":"flight","unit_departure_location":"MRS","unit_departure_to":"Santiago, Chile","unit_departure_date":"2026-09-19","unit_departure_time":"17:00","airport_buffer_minutes":180}'::jsonb)

ON CONFLICT (id) DO NOTHING;


-- ────────────────────────────────────────────────────────────────────────
-- Verify
-- ────────────────────────────────────────────────────────────────────────
SELECT COUNT(DISTINCT meta->>'person_id') AS travelers,
       COUNT(*)                            AS unit_rows
FROM   public.travelers;
-- → 16 travelers, 38 unit rows
