-- ============================================================================
-- Japan LUXURY + BOND travelers seed — 12 people, 1 unit each (one place only)
--
-- High-luxury inbound travelers that REQUIRE a bond. Single destination per
-- person (unit_total = 1), 4–7 days; the higher the bond, the more days and
-- the higher the budget. Budgets are YEN, stored in the legacy *_eur meta keys
-- + budget_per_day / hotel_budget columns (renderer just prefixes ¥).
--
-- requires_bond = true on every row; bond_amount per the agreed ladder:
--   ¥12,000 ×1 · ¥20,000 ×1 · ¥60,000 ×2 · ¥140,000 ×2 · ¥270,000 ×2
--   ¥460,000 ×2 · ¥570,000 ×2   (= ¥3,032,000 total held)
--
-- Transport is NOT briefed: each person arrives/departs by international flight
-- (the only fixed leg); private ground transport is arranged off-platform, so
-- the planner just picks GO Taxi per leg to capture route + duration.
-- Every traveler shares must_avoid = "Tourist traps, crowds, anything generic".
--
-- Rollback:  DELETE FROM public.travelers WHERE meta->>'seed_batch' = 'lux-jp-bond-01';
-- Safe to re-run (the DO block below clears lux-jp-bond-01 first).
-- ============================================================================

ALTER TABLE public.travelers ADD COLUMN IF NOT EXISTS meta           jsonb;
ALTER TABLE public.travelers ADD COLUMN IF NOT EXISTS budget_per_day int;
ALTER TABLE public.travelers ADD COLUMN IF NOT EXISTS hotel_budget   int;
ALTER TABLE public.travelers ADD COLUMN IF NOT EXISTS market         text;

-- Re-run cleanup: remove any prior lux-jp-bond-01 rows + their dependents
-- (FKs are RESTRICT, not CASCADE — peel the deepest dependency first).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema='public' AND table_name='travelers' AND column_name='meta') THEN
    DELETE FROM public.itinerary_items WHERE plan_id IN (
      SELECT id FROM public.plans WHERE traveler_id IN (
        SELECT id FROM public.travelers WHERE meta->>'seed_batch' = 'lux-jp-bond-01'));
    DELETE FROM public.plans WHERE traveler_id IN (
      SELECT id FROM public.travelers WHERE meta->>'seed_batch' = 'lux-jp-bond-01');
    DELETE FROM public.travelers WHERE meta->>'seed_batch' = 'lux-jp-bond-01';
  END IF;
END $$;

INSERT INTO public.travelers
  (id, name, phone, destination, traveler_type, arrival_date, arrival_time, duration, group_size, special_notes, status, planner_payout, requires_bond, bond_amount, budget_per_day, hotel_budget, meta) VALUES

-- ── 01 · Charlotte Bennett · Solo · Kyoto · ¥12,000 bond · 4D3N ──
('c0000001-0000-4000-8000-000100010000','Charlotte Bennett','+44 7700 900482','Kyoto','solo','2026-08-01','14:30','4D3N',1,'Treating myself to a few slow days in Kyoto after a relentless year — refined kaiseki, quiet temple mornings, and a room worth staying in.','unassigned',9000,true,12000,70000,140000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0001","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-01","trip_end_date":"2026-08-04","trip_total_duration":"4D3N","origin_country":"United Kingdom","origin_city":"London","ages":[38],"languages":["English (native)"],"occasion":"Solo reset after a relentless year, a few refined days in Kyoto","budget_tier":"luxury","daily_spend_per_pax_eur":70000,"hotel_budget_per_night_eur":140000,"hotel_budget_per_night_pax_eur":140000,"pace":"slow","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["temples_shrines","gardens","food_dining","photography"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 deluxe room · 1 guest","accommodation_musthaves":["Central location","Garden view","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Kaiseki","Sushi","Wagyu"],"unit_arrival_method":"flight","unit_arrival_location":"Kansai International Airport (KIX)","unit_arrival_from":"London, United Kingdom","unit_departure_method":"flight","unit_departure_location":"Kansai International Airport (KIX)","unit_departure_to":"London, United Kingdom","unit_departure_date":"2026-08-04","unit_departure_time":"18:40","airport_buffer_minutes":180}'::jsonb),

-- ── 02 · Daniel & Grace Park · Couple · Tokyo · ¥20,000 bond · 4D3N ──
('c0000001-0000-4000-8000-000200010000','Daniel & Grace Park','+1 415 555 0173','Tokyo','couple','2026-08-13','15:00','4D3N',2,'Our anniversary. We are serious about food — omakase counters, one unforgettable tasting menu, and a high-floor room with a view.','unassigned',11000,true,20000,85000,190000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0002","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-13","trip_end_date":"2026-08-16","trip_total_duration":"4D3N","origin_country":"United States","origin_city":"San Francisco","ages":[41,39],"languages":["English (native)","Korean (conversational)"],"occasion":"Anniversary trip for a couple who take food seriously","budget_tier":"luxury","daily_spend_per_pax_eur":85000,"hotel_budget_per_night_eur":190000,"hotel_budget_per_night_pax_eur":95000,"pace":"moderate","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["food_dining","architecture","shopping","art_museums"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"been_before","booking_authority":"planner_recommends","room_type":"1 double room · 2 guests","accommodation_musthaves":["High floor","City view","Club lounge access"],"dining_style":"fine_dining","cuisine_interests":["Sushi","Wagyu","Teppanyaki"],"unit_arrival_method":"flight","unit_arrival_location":"Haneda Airport (HND)","unit_arrival_from":"San Francisco, United States","unit_departure_method":"flight","unit_departure_location":"Haneda Airport (HND)","unit_departure_to":"San Francisco, United States","unit_departure_date":"2026-08-16","unit_departure_time":"19:10","airport_buffer_minutes":180}'::jsonb),

-- ── 03 · Arjun & Priya Mehta · Honeymoon · Hakone · ¥60,000 bond · 5D4N ──
('c0000001-0000-4000-8000-000300010000','Arjun & Priya Mehta','+971 50 412 8836','Hakone','honeymoon','2026-08-02','14:00','5D4N',2,'Our honeymoon. A private open-air bath, in-room kaiseki, and nothing on the schedule but each other.','unassigned',14000,true,60000,100000,280000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0003","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-02","trip_end_date":"2026-08-06","trip_total_duration":"5D4N","origin_country":"United Arab Emirates","origin_city":"Dubai","ages":[31,29],"languages":["English (fluent)","Hindi"],"occasion":"Honeymoon — private onsen, in-room kaiseki, total privacy","budget_tier":"luxury","daily_spend_per_pax_eur":100000,"hotel_budget_per_night_eur":280000,"hotel_budget_per_night_pax_eur":140000,"pace":"slow","intensity":"moderate","daily_timing":"late","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["onsen","food_dining","nature_hiking","photography"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 room with private open-air bath · 2 guests","accommodation_musthaves":["Private open-air bath","Half-board (dinner & breakfast)","Valley view"],"dining_style":"fine_dining","cuisine_interests":["Kaiseki","Wagyu","Sake"],"unit_arrival_method":"flight","unit_arrival_location":"Haneda Airport (HND)","unit_arrival_from":"Dubai, United Arab Emirates","unit_departure_method":"flight","unit_departure_location":"Haneda Airport (HND)","unit_departure_to":"Dubai, United Arab Emirates","unit_departure_date":"2026-08-06","unit_departure_time":"18:20","airport_buffer_minutes":180}'::jsonb),

-- ── 04 · Chen Wei · Solo · Kanazawa · ¥60,000 bond · 5D4N ──
('c0000001-0000-4000-8000-000400010000','Chen Wei','+65 8123 7741','Kanazawa','solo','2026-08-05','14:15','5D4N',1,'A craft-and-art trip to Kanazawa — gold-leaf workshops, the old geisha streets, and the best sushi counter you can get me into.','unassigned',14000,true,60000,105000,200000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0004","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-05","trip_end_date":"2026-08-09","trip_total_duration":"5D4N","origin_country":"Singapore","origin_city":"Singapore","ages":[47],"languages":["English (fluent)","Mandarin"],"occasion":"Craft-and-art pilgrimage to Kanazawa","budget_tier":"luxury","daily_spend_per_pax_eur":105000,"hotel_budget_per_night_eur":200000,"hotel_budget_per_night_pax_eur":200000,"pace":"moderate","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["art_museums","local_culture","food_dining","history"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"been_before","booking_authority":"planner_recommends","room_type":"1 room with private open-air bath · 1 guest","accommodation_musthaves":["Central location","Private open-air bath","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Sushi","Kaiseki","Seafood"],"unit_arrival_method":"flight","unit_arrival_location":"Komatsu Airport (KMQ)","unit_arrival_from":"Singapore","unit_departure_method":"flight","unit_departure_location":"Komatsu Airport (KMQ)","unit_departure_to":"Singapore","unit_departure_date":"2026-08-09","unit_departure_time":"17:50","airport_buffer_minutes":180}'::jsonb),

-- ── 05 · Olivia & James Thompson · Couple · Kyoto · ¥140,000 bond · 5D4N ──
('c0000001-0000-4000-8000-000500010000','Olivia & James Thompson','+61 412 884 037','Kyoto','couple','2026-08-08','14:30','5D4N',2,'Twenty-five years married. We would love an Aman-level stay, a private tea ceremony, and Kyoto gardens without the crowds.','unassigned',20000,true,140000,130000,360000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0005","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-08","trip_end_date":"2026-08-12","trip_total_duration":"5D4N","origin_country":"Australia","origin_city":"Melbourne","ages":[55,52],"languages":["English (native)"],"occasion":"25th wedding anniversary","budget_tier":"luxury","daily_spend_per_pax_eur":130000,"hotel_budget_per_night_eur":360000,"hotel_budget_per_night_pax_eur":180000,"pace":"slow","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["temples_shrines","gardens","food_dining","art_museums"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 suite · 2 guests","accommodation_musthaves":["Suite","Garden view","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Kaiseki","Sushi","Wagyu"],"unit_arrival_method":"flight","unit_arrival_location":"Kansai International Airport (KIX)","unit_arrival_from":"Melbourne, Australia","unit_departure_method":"flight","unit_departure_location":"Kansai International Airport (KIX)","unit_departure_to":"Melbourne, Australia","unit_departure_date":"2026-08-12","unit_departure_time":"20:05","airport_buffer_minutes":180}'::jsonb),

-- ── 06 · Al-Rashid family · Family (4) · Okinawa · ¥140,000 bond · 5D4N ──
('c0000001-0000-4000-8000-000600010000','Al-Rashid family','+966 50 318 4427','Okinawa','family','2026-08-11','14:00','5D4N',4,'Summer with the children. We need a beachfront family suite, halal-friendly dining, and easy days by the water in Okinawa.','unassigned',20000,true,140000,125000,360000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0006","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-11","trip_end_date":"2026-08-15","trip_total_duration":"5D4N","origin_country":"Saudi Arabia","origin_city":"Riyadh","ages":[44,40,12,9],"languages":["Arabic","English (fluent)"],"occasion":"Summer family holiday in Okinawa","budget_tier":"luxury","daily_spend_per_pax_eur":125000,"hotel_budget_per_night_eur":360000,"hotel_budget_per_night_pax_eur":90000,"pace":"moderate","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"halal","mobility":"none","interests":["beach","food_dining","shopping","local_culture"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 family suite · 4 guests","accommodation_musthaves":["Beachfront","Family suite","Halal-friendly"],"dining_style":"fine_dining","cuisine_interests":["Wagyu","Seafood","Teppanyaki"],"unit_arrival_method":"flight","unit_arrival_location":"Naha Airport (OKA)","unit_arrival_from":"Riyadh, Saudi Arabia","unit_departure_method":"flight","unit_departure_location":"Naha Airport (OKA)","unit_departure_to":"Riyadh, Saudi Arabia","unit_departure_date":"2026-08-15","unit_departure_time":"18:15","airport_buffer_minutes":180}'::jsonb),

-- ── 07 · Sophie & Lucas Müller · Honeymoon · Kyoto · ¥270,000 bond · 6D5N ──
('c0000001-0000-4000-8000-000700010000','Sophie & Lucas Müller','+49 151 2847 6630','Kyoto','honeymoon','2026-08-01','14:30','6D5N',2,'Our honeymoon — a riverside suite, one Michelin kaiseki night, and an evening with a geiko if it can be arranged.','unassigned',30000,true,270000,170000,520000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0007","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-01","trip_end_date":"2026-08-06","trip_total_duration":"6D5N","origin_country":"Germany","origin_city":"Munich","ages":[36,34],"languages":["German","English (fluent)"],"occasion":"Honeymoon in Kyoto","budget_tier":"luxury","daily_spend_per_pax_eur":170000,"hotel_budget_per_night_eur":520000,"hotel_budget_per_night_pax_eur":260000,"pace":"slow","intensity":"moderate","daily_timing":"late","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["temples_shrines","onsen","gardens","food_dining"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 suite · 2 guests","accommodation_musthaves":["Suite","Riverside","Private open-air bath"],"dining_style":"fine_dining","cuisine_interests":["Kaiseki","Sushi","Wagyu"],"unit_arrival_method":"flight","unit_arrival_location":"Kansai International Airport (KIX)","unit_arrival_from":"Munich, Germany","unit_departure_method":"flight","unit_departure_location":"Kansai International Airport (KIX)","unit_departure_to":"Munich, Germany","unit_departure_date":"2026-08-06","unit_departure_time":"19:40","airport_buffer_minutes":180}'::jsonb),

-- ── 08 · Wong family-office group · Group (5) · Tokyo · ¥270,000 bond · 6D5N ──
('c0000001-0000-4000-8000-000800010000','Wong family-office group','+852 6123 8847','Tokyo','group','2026-08-04','15:00','6D5N',5,'Celebrating a milestone as a group of five. Connecting suites, private dining, and a few experiences money usually cannot buy.','unassigned',30000,true,270000,160000,680000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0008","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-04","trip_end_date":"2026-08-09","trip_total_duration":"6D5N","origin_country":"Hong Kong","origin_city":"Hong Kong","ages":[58,55,33,31,29],"languages":["Cantonese","English (fluent)","Mandarin"],"occasion":"Milestone celebration for a family group of five","budget_tier":"luxury","daily_spend_per_pax_eur":160000,"hotel_budget_per_night_eur":680000,"hotel_budget_per_night_pax_eur":136000,"pace":"moderate","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["food_dining","shopping","art_museums","nightlife"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"been_before","booking_authority":"planner_recommends","room_type":"3 connecting suites · 5 guests","accommodation_musthaves":["Connecting rooms","Club lounge access","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Sushi","Wagyu","Kaiseki"],"unit_arrival_method":"flight","unit_arrival_location":"Haneda Airport (HND)","unit_arrival_from":"Hong Kong","unit_departure_method":"flight","unit_departure_location":"Haneda Airport (HND)","unit_departure_to":"Hong Kong","unit_departure_date":"2026-08-09","unit_departure_time":"20:25","airport_buffer_minutes":180}'::jsonb),

-- ── 09 · Sterling family · Family (4) · Niseko · ¥460,000 bond · 6D5N ──
('c0000001-0000-4000-8000-000900010000','Sterling family','+1 212 555 0148','Niseko','family','2026-08-07','14:00','6D5N',4,'Green-season Niseko with the teenagers — a two-bedroom suite with onsen, mountain air, and proper food after a day outdoors.','unassigned',45000,true,460000,210000,760000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0009","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-07","trip_end_date":"2026-08-12","trip_total_duration":"6D5N","origin_country":"United States","origin_city":"New York","ages":[48,46,16,14],"languages":["English (native)"],"occasion":"Green-season family trip to Niseko with teenagers","budget_tier":"luxury","daily_spend_per_pax_eur":210000,"hotel_budget_per_night_eur":760000,"hotel_budget_per_night_pax_eur":190000,"pace":"active","intensity":"active","daily_timing":"early","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["nature_hiking","onsen","food_dining","photography"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"been_before","booking_authority":"planner_recommends","room_type":"1 two-bedroom suite · 4 guests","accommodation_musthaves":["Two bedrooms","Onsen","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Wagyu","Seafood","Kaiseki"],"unit_arrival_method":"flight","unit_arrival_location":"New Chitose Airport (CTS)","unit_arrival_from":"New York, United States","unit_departure_method":"flight","unit_departure_location":"New Chitose Airport (CTS)","unit_departure_to":"New York, United States","unit_departure_date":"2026-08-12","unit_departure_time":"18:50","airport_buffer_minutes":180}'::jsonb),

-- ── 10 · Isabella & Matteo Romano · Couple · Hakone · ¥460,000 bond · 6D5N ──
('c0000001-0000-4000-8000-001000010000','Isabella & Matteo Romano','+39 333 472 9185','Hakone','couple','2026-08-10','14:15','6D5N',2,'A special anniversary in Hakone — a grand suite with a private bath, the open-air museum, and Fuji on a clear morning.','unassigned',45000,true,460000,200000,720000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0010","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-10","trip_end_date":"2026-08-15","trip_total_duration":"6D5N","origin_country":"Italy","origin_city":"Milan","ages":[61,58],"languages":["Italian","English (intermediate)"],"occasion":"Special anniversary in Hakone","budget_tier":"luxury","daily_spend_per_pax_eur":200000,"hotel_budget_per_night_eur":720000,"hotel_budget_per_night_pax_eur":360000,"pace":"slow","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["onsen","art_museums","nature_hiking","food_dining"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 suite with private open-air bath · 2 guests","accommodation_musthaves":["Private open-air bath","Suite","Mt. Fuji view"],"dining_style":"fine_dining","cuisine_interests":["Kaiseki","Wagyu","Sushi"],"unit_arrival_method":"flight","unit_arrival_location":"Haneda Airport (HND)","unit_arrival_from":"Milan, Italy","unit_departure_method":"flight","unit_departure_location":"Haneda Airport (HND)","unit_departure_to":"Milan, Italy","unit_departure_date":"2026-08-15","unit_departure_time":"19:20","airport_buffer_minutes":180}'::jsonb),

-- ── 11 · Aisha & Khalid Al-Maktoum · Honeymoon · Kyoto · ¥570,000 bond · 7D6N ──
('c0000001-0000-4000-8000-001100010000','Aisha & Khalid Al-Maktoum','+971 56 902 3318','Kyoto','honeymoon','2026-08-03','14:30','7D6N',2,'Our honeymoon, no expense spared — an Aman suite, a private garden, and a quiet after-hours temple moment for the two of us.','unassigned',60000,true,570000,260000,880000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0011","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-03","trip_end_date":"2026-08-09","trip_total_duration":"7D6N","origin_country":"United Arab Emirates","origin_city":"Abu Dhabi","ages":[33,30],"languages":["Arabic","English (fluent)"],"occasion":"Honeymoon, no expense spared","budget_tier":"luxury","daily_spend_per_pax_eur":260000,"hotel_budget_per_night_eur":880000,"hotel_budget_per_night_pax_eur":440000,"pace":"slow","intensity":"moderate","daily_timing":"late","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"none","interests":["temples_shrines","gardens","food_dining","local_culture"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"first_time","booking_authority":"planner_recommends","room_type":"1 suite · 2 guests","accommodation_musthaves":["Suite","Private garden","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Kaiseki","Sushi","Wagyu"],"unit_arrival_method":"flight","unit_arrival_location":"Kansai International Airport (KIX)","unit_arrival_from":"Abu Dhabi, United Arab Emirates","unit_departure_method":"flight","unit_departure_location":"Kansai International Airport (KIX)","unit_departure_to":"Abu Dhabi, United Arab Emirates","unit_departure_date":"2026-08-09","unit_departure_time":"20:10","airport_buffer_minutes":180}'::jsonb),

-- ── 12 · Zhang family (multigenerational) · Family (5) · Tokyo · ¥570,000 bond · 7D6N ──
('c0000001-0000-4000-8000-001200010000','Zhang family','+86 138 1672 4490','Tokyo','family','2026-08-10','15:00','7D6N',5,'Three generations, one trip. We need adjoining, barrier-free suites for my father, and calm, accessible days everyone can share.','unassigned',60000,true,570000,250000,1000000,
 '{"seed_batch":"lux-jp-bond-01","market":"japan","person_id":"0012","unit_order":1,"unit_total":1,"trip_start_date":"2026-08-10","trip_end_date":"2026-08-16","trip_total_duration":"7D6N","origin_country":"China","origin_city":"Shanghai","ages":[70,45,43,15,11],"languages":["Mandarin","English (intermediate)"],"occasion":"Three-generation celebration trip","budget_tier":"luxury","daily_spend_per_pax_eur":250000,"hotel_budget_per_night_eur":1000000,"hotel_budget_per_night_pax_eur":200000,"pace":"slow","intensity":"moderate","daily_timing":"standard","splurge_willingness":"luxury_throughout","dietary_restrictions":"none","mobility":"limited","interests":["food_dining","shopping","local_culture","gardens"],"must_avoid":"Tourist traps, crowds, anything generic","previous_visits_japan":"been_before","booking_authority":"planner_recommends","room_type":"3 connecting suites · 5 guests (barrier-free)","accommodation_musthaves":["Connecting rooms","Barrier-free","Quiet room"],"dining_style":"fine_dining","cuisine_interests":["Wagyu","Sushi","Kaiseki"],"unit_arrival_method":"flight","unit_arrival_location":"Haneda Airport (HND)","unit_arrival_from":"Shanghai, China","unit_departure_method":"flight","unit_departure_location":"Haneda Airport (HND)","unit_departure_to":"Shanghai, China","unit_departure_date":"2026-08-16","unit_departure_time":"18:35","airport_buffer_minutes":180}'::jsonb);

-- Mirror market onto the top-level column (admin filter may prefer it).
UPDATE public.travelers SET market = 'japan' WHERE meta->>'seed_batch' = 'lux-jp-bond-01';

-- Verify (optional):
--   SELECT name, destination, duration, bond_amount, budget_per_day, hotel_budget
--     FROM public.travelers WHERE meta->>'seed_batch' = 'lux-jp-bond-01'
--     ORDER BY bond_amount;
